// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import SpecPayments from 'spec-payments-stainless-demo';
import { Response } from 'node-fetch';

const client = new SpecPayments({
  accessToken: 'My Access Token',
  apiKey: 'My API Key',
  adminKey: 'My Admin Key',
  clientId: 'My Client ID',
  clientSecret: 'My Client Secret',
  baseURL: process.env['TEST_API_BASE_URL'] ?? 'http://127.0.0.1:4010',
});

describe('resource sessions', () => {
  test('retrieve', async () => {
    const responsePromise = client.sessions.retrieve('session_id');
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  test('retrieve: request options instead of params are passed correctly', async () => {
    // ensure the request options are being passed correctly by passing an invalid HTTP method in order to cause an error
    await expect(
      client.sessions.retrieve('session_id', { path: '/_stainless_unknown_path' }),
    ).rejects.toThrow(SpecPayments.NotFoundError);
  });

  test('retrieve: request options and params are passed correctly', async () => {
    // ensure the request options are being passed correctly by passing an invalid HTTP method in order to cause an error
    await expect(
      client.sessions.retrieve(
        'session_id',
        { includes: ['events.request_headers', 'initiating_system_request_headers'] },
        { path: '/_stainless_unknown_path' },
      ),
    ).rejects.toThrow(SpecPayments.NotFoundError);
  });

  test('update: only required params', async () => {
    const responsePromise = client.sessions.update('session_id', { order: {} });
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  test('update: required and optional params', async () => {
    const response = await client.sessions.update('session_id', {
      order: {
        amount: 72200,
        billing_address: {
          address_line: 'address_line',
          address_line_2: 'address_line_2',
          business_name: 'business_name',
          co_address: 'Land Lord',
          comment: 'comment',
          cost_center: 'cost_center',
          country: 'NO',
          customer_reference: 'customer_reference',
          email: 'email',
          first_name: 'John',
          last_name: 'Doe',
          latitude: 0,
          longitude: 0,
          organization_number: 'organization_number',
          organization_type: 'organization_type',
          phone_number: 'phone_number',
          postal_code: '0349',
          postal_place: 'Oslo',
        },
        currency: 'NOK',
        discount_codes: ['SUMMER20', 'SUMMER20', 'SUMMER20'],
        discount_lines: [
          {
            amount: 4400,
            description: 'description',
            discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
            discount_type: 'customer',
            line_id: 1,
            percentage: 44,
          },
          {
            amount: 4400,
            description: 'description',
            discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
            discount_type: 'customer',
            line_id: 1,
            percentage: 44,
          },
          {
            amount: 4400,
            description: 'description',
            discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
            discount_type: 'customer',
            line_id: 1,
            percentage: 44,
          },
        ],
        items: [
          {
            id: '10',
            amount: 2000,
            description: 'Forsvinnignspølse',
            discount_lines: [
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
            ],
            eligible_for_discount: true,
            emd: {
              event: [
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
              ],
              marketplace_order: {
                seller_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  product_category: 'Phones',
                  sub_merchant_id: 'Marketbrick Ltd.',
                  product_name: 'iPhone 14 Pro Max',
                  seller_rating: 5,
                  unique_account_identifier_seller: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
                winner_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  unique_account_identifier_winner: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
              },
              subscription: {
                customer_account_info: {
                  account_last_modified: 'account_last_modified',
                  account_registration_date: 'account_registration_date',
                  unique_account_identifier: 'Adam Adamsson',
                },
                subscription: {
                  auto_renewal_of_subscription: true,
                  end_time: '2019-12-27T18:11:19.117Z',
                  start_time: '2019-12-27T18:11:19.117Z',
                  subscription_name: 'Contact lenses',
                  affiliate_name: 'Klarna affiliate',
                },
              },
              travel: {
                air_reservation_details: {
                  itinerary: [
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                bus_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                car_rental_reservation_details: {
                  drivers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  itinerary: [
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  pnr: 'VH67899',
                },
                ferry_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                hotel_reservation_details: {
                  itinerary: [
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                train_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
              },
            },
            fee_split: { type: 'proportional', destinations: ['string'] },
            groups: [{ id: 'B234', name: 'Stol' }],
            is_changed: true,
            line_id: '1',
            quantity: 2,
            splits: [
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
            ],
            thumbnail_url: 'https://example.com',
            type: 'physical',
            unit_dimensional_weight: 0,
            unit_volume: 0,
            unit_weight: 0,
            vat: 20,
            vat_amount: 400,
          },
          {
            id: '6',
            amount: 6600,
            description: 'Vissvossafår på neppebrød',
            discount_lines: [
              {
                amount: 4400,
                description: 'Vossafestpris',
                discount_id: 'ed960ace-eb16-4e2e-ae52-b27647ccae8d',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
            ],
            eligible_for_discount: true,
            emd: {
              event: [
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
              ],
              marketplace_order: {
                seller_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  product_category: 'Phones',
                  sub_merchant_id: 'Marketbrick Ltd.',
                  product_name: 'iPhone 14 Pro Max',
                  seller_rating: 5,
                  unique_account_identifier_seller: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
                winner_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  unique_account_identifier_winner: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
              },
              subscription: {
                customer_account_info: {
                  account_last_modified: 'account_last_modified',
                  account_registration_date: 'account_registration_date',
                  unique_account_identifier: 'Adam Adamsson',
                },
                subscription: {
                  auto_renewal_of_subscription: true,
                  end_time: '2019-12-27T18:11:19.117Z',
                  start_time: '2019-12-27T18:11:19.117Z',
                  subscription_name: 'Contact lenses',
                  affiliate_name: 'Klarna affiliate',
                },
              },
              travel: {
                air_reservation_details: {
                  itinerary: [
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                bus_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                car_rental_reservation_details: {
                  drivers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  itinerary: [
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  pnr: 'VH67899',
                },
                ferry_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                hotel_reservation_details: {
                  itinerary: [
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                train_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
              },
            },
            fee_split: { type: 'proportional', destinations: ['string'] },
            groups: [{ id: 'B234', name: 'Stol' }],
            is_changed: true,
            line_id: '2',
            quantity: 2,
            splits: [
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
            ],
            thumbnail_url: 'https://example.com',
            type: 'physical',
            unit_dimensional_weight: 0,
            unit_volume: 0,
            unit_weight: 0,
            vat: 20,
            vat_amount: 400,
          },
          {
            id: '1',
            amount: 59700,
            description: 'Luftboller',
            discount_lines: [
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
            ],
            eligible_for_discount: true,
            emd: {
              event: [
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
              ],
              marketplace_order: {
                seller_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  product_category: 'Phones',
                  sub_merchant_id: 'Marketbrick Ltd.',
                  product_name: 'iPhone 14 Pro Max',
                  seller_rating: 5,
                  unique_account_identifier_seller: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
                winner_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  unique_account_identifier_winner: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
              },
              subscription: {
                customer_account_info: {
                  account_last_modified: 'account_last_modified',
                  account_registration_date: 'account_registration_date',
                  unique_account_identifier: 'Adam Adamsson',
                },
                subscription: {
                  auto_renewal_of_subscription: true,
                  end_time: '2019-12-27T18:11:19.117Z',
                  start_time: '2019-12-27T18:11:19.117Z',
                  subscription_name: 'Contact lenses',
                  affiliate_name: 'Klarna affiliate',
                },
              },
              travel: {
                air_reservation_details: {
                  itinerary: [
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                bus_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                car_rental_reservation_details: {
                  drivers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  itinerary: [
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  pnr: 'VH67899',
                },
                ferry_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                hotel_reservation_details: {
                  itinerary: [
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                train_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
              },
            },
            fee_split: { type: 'proportional', destinations: ['string'] },
            groups: [{ id: 'B234', name: 'Stol' }],
            is_changed: true,
            line_id: '3',
            quantity: 3,
            splits: [
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
            ],
            thumbnail_url: 'https://example.com',
            type: 'physical',
            unit_dimensional_weight: 0,
            unit_volume: 0,
            unit_weight: 0,
            vat: 20,
            vat_amount: 400,
          },
        ],
        merchant_reference_2: 'merchant_reference_2',
        partial_payment: true,
        shipping_address: {
          address_line: 'address_line',
          address_line_2: 'address_line_2',
          business_name: 'business_name',
          co_address: 'Land Lord',
          comment: 'comment',
          cost_center: 'cost_center',
          country: 'NO',
          customer_reference: 'customer_reference',
          email: 'email',
          first_name: 'John',
          last_name: 'Doe',
          latitude: 0,
          longitude: 0,
          organization_number: 'organization_number',
          organization_type: 'organization_type',
          phone_number: 'phone_number',
          postal_code: '0349',
          postal_place: 'Oslo',
        },
        shipping_option: {
          id: 'bring-pick-up-00001',
          amount: 3900,
          line_id: 'bring-pick-up-00001-location-0a1f6b',
          operator: 'Bring',
          title: 'Standard',
          countries: ['NO', 'NO', 'NO'],
          delivery_method: 'delivery',
          description: 'Pick up at your nearest postal office',
          environmental_data: {
            description: 'Fossil free',
            details: [
              { label: 'Carbon offset', value: '1KG CO2' },
              { label: 'Carbon offset', value: '1KG CO2' },
              { label: 'Carbon offset', value: '1KG CO2' },
            ],
          },
          eta: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
          fee_split: { type: 'proportional', destinations: ['string'] },
          metadata: '',
          operator_product_id: 'pick-up-00001-location-0a1f6b',
          pick_up_address: {
            address_line: 'address_line',
            address_line_2: 'address_line_2',
            business_name: 'business_name',
            co_address: 'Land Lord',
            comment: 'comment',
            cost_center: 'cost_center',
            country: 'NO',
            customer_reference: 'customer_reference',
            distance: 0,
            email: 'email',
            first_name: 'John',
            last_name: 'Doe',
            latitude: 0,
            longitude: 0,
            organization_number: 'organization_number',
            organization_type: 'organization_type',
            phone_number: 'phone_number',
            postal_code: '0349',
            postal_place: 'Oslo',
          },
          splits: [
            { amount: 29700, payout_destination_id: 'P000000001' },
            { amount: 29700, payout_destination_id: 'P000000001' },
            { amount: 29700, payout_destination_id: 'P000000001' },
          ],
          thumbnail_url: 'https://example.com',
          time_slot: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
          vat: 25,
          vat_amount: 975,
        },
        store: {
          id: 'sc029',
          address: {
            address_line: 'Sommerkroveien 34',
            country: 'NO',
            postal_place: 'Oslo',
            address_line_2: 'PB 123',
            postal_code: '0349',
          },
          bax: '102603',
          business_name: 'SC Oslo AS',
          chain: 'SuperChain',
          email: 'contact@superchain.com',
          gln: '5790001398644',
          mcc: '5814',
          name: 'SC Oslo',
          organization_number: '123456789MVA',
          phone_number: '+4738260107',
          terminal_id: 'T0292',
        },
        vat_amount: 13660,
      },
      force_shipping_address_callback: true,
      update_without_lock: true,
      express: {
        shipping_options: [
          {
            id: 'bring-pick-up-00001',
            amount: 3900,
            line_id: 'bring-pick-up-00001-location-0a1f6b',
            operator: 'Bring',
            title: 'Standard',
            countries: ['NO', 'NO', 'NO'],
            delivery_method: 'delivery',
            description: 'Pick up at your nearest postal office',
            environmental_data: {
              description: 'Fossil free',
              details: [
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
              ],
            },
            eta: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            metadata: '',
            operator_product_id: 'pick-up-00001-location-0a1f6b',
            pick_up_address: {
              address_line: 'address_line',
              address_line_2: 'address_line_2',
              business_name: 'business_name',
              co_address: 'Land Lord',
              comment: 'comment',
              cost_center: 'cost_center',
              country: 'NO',
              customer_reference: 'customer_reference',
              distance: 0,
              email: 'email',
              first_name: 'John',
              last_name: 'Doe',
              latitude: 0,
              longitude: 0,
              organization_number: 'organization_number',
              organization_type: 'organization_type',
              phone_number: 'phone_number',
              postal_code: '0349',
              postal_place: 'Oslo',
            },
            thumbnail_url: 'https://example.com',
            time_slot: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            vat: 25,
            vat_amount: 975,
          },
          {
            id: 'bring-pick-up-00001',
            amount: 3900,
            line_id: 'bring-pick-up-00001-location-0a1f6b',
            operator: 'Bring',
            title: 'Standard',
            countries: ['NO', 'NO', 'NO'],
            delivery_method: 'delivery',
            description: 'Pick up at your nearest postal office',
            environmental_data: {
              description: 'Fossil free',
              details: [
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
              ],
            },
            eta: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            metadata: '',
            operator_product_id: 'pick-up-00001-location-0a1f6b',
            pick_up_address: {
              address_line: 'address_line',
              address_line_2: 'address_line_2',
              business_name: 'business_name',
              co_address: 'Land Lord',
              comment: 'comment',
              cost_center: 'cost_center',
              country: 'NO',
              customer_reference: 'customer_reference',
              distance: 0,
              email: 'email',
              first_name: 'John',
              last_name: 'Doe',
              latitude: 0,
              longitude: 0,
              organization_number: 'organization_number',
              organization_type: 'organization_type',
              phone_number: 'phone_number',
              postal_code: '0349',
              postal_place: 'Oslo',
            },
            thumbnail_url: 'https://example.com',
            time_slot: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            vat: 25,
            vat_amount: 975,
          },
          {
            id: 'bring-pick-up-00001',
            amount: 3900,
            line_id: 'bring-pick-up-00001-location-0a1f6b',
            operator: 'Bring',
            title: 'Standard',
            countries: ['NO', 'NO', 'NO'],
            delivery_method: 'delivery',
            description: 'Pick up at your nearest postal office',
            environmental_data: {
              description: 'Fossil free',
              details: [
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
              ],
            },
            eta: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            metadata: '',
            operator_product_id: 'pick-up-00001-location-0a1f6b',
            pick_up_address: {
              address_line: 'address_line',
              address_line_2: 'address_line_2',
              business_name: 'business_name',
              co_address: 'Land Lord',
              comment: 'comment',
              cost_center: 'cost_center',
              country: 'NO',
              customer_reference: 'customer_reference',
              distance: 0,
              email: 'email',
              first_name: 'John',
              last_name: 'Doe',
              latitude: 0,
              longitude: 0,
              organization_number: 'organization_number',
              organization_type: 'organization_type',
              phone_number: 'phone_number',
              postal_code: '0349',
              postal_place: 'Oslo',
            },
            thumbnail_url: 'https://example.com',
            time_slot: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            vat: 25,
            vat_amount: 975,
          },
        ],
        shipping_mode: 'shipping_required',
      },
      remove_lock: true,
      'Dintero-Feature-Toggles': ['strict-session-amounts'],
      'Dintero-System-Name': 'Dintero-System-Name',
      'Dintero-System-Plugin-Name': 'Dintero-System-Plugin-Name',
      'Dintero-System-Plugin-Version': 'Dintero-System-Plugin-Version',
      'Dintero-System-Version': 'Dintero-System-Version',
    });
  });

  test('cancel', async () => {
    const responsePromise = client.sessions.cancel('session_id');
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  test('cancel: request options instead of params are passed correctly', async () => {
    // ensure the request options are being passed correctly by passing an invalid HTTP method in order to cause an error
    await expect(client.sessions.cancel('session_id', { path: '/_stainless_unknown_path' })).rejects.toThrow(
      SpecPayments.NotFoundError,
    );
  });

  test('cancel: request options and params are passed correctly', async () => {
    // ensure the request options are being passed correctly by passing an invalid HTTP method in order to cause an error
    await expect(
      client.sessions.cancel(
        'session_id',
        {
          'Dintero-System-Name': 'Dintero-System-Name',
          'Dintero-System-Plugin-Name': 'Dintero-System-Plugin-Name',
          'Dintero-System-Plugin-Version': 'Dintero-System-Plugin-Version',
          'Dintero-System-Version': 'Dintero-System-Version',
        },
        { path: '/_stainless_unknown_path' },
      ),
    ).rejects.toThrow(SpecPayments.NotFoundError);
  });

  test('pay', async () => {
    const responsePromise = client.sessions.pay({});
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  test('paymentToken: only required params', async () => {
    const responsePromise = client.sessions.paymentToken({
      session: {
        order: { currency: 'NOK', merchant_reference: 'merchant_reference' },
        url: { return_url: 'https://example.com/accept' },
      },
      token_provider: { payment_product_type: 'payment_product_type' },
    });
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  test('paymentToken: required and optional params', async () => {
    const response = await client.sessions.paymentToken({
      session: {
        order: {
          currency: 'NOK',
          merchant_reference: 'merchant_reference',
          merchant_reference_2: 'merchant_reference_2',
          store: {
            id: 'sc029',
            address: {
              address_line: 'Sommerkroveien 34',
              country: 'NO',
              postal_place: 'Oslo',
              address_line_2: 'PB 123',
              postal_code: '0349',
            },
            bax: '102603',
            business_name: 'SC Oslo AS',
            chain: 'SuperChain',
            email: 'contact@superchain.com',
            gln: '5790001398644',
            mcc: '5814',
            name: 'SC Oslo',
            organization_number: '123456789MVA',
            phone_number: '+4738260107',
            terminal_id: 'T0292',
          },
        },
        url: {
          return_url: 'https://example.com/accept',
          callback_url: 'https://example.com/callback?method=GET',
          merchant_terms_url: 'https://example.com/terms.html',
        },
        configuration: {
          theme: {
            backdrop: 'backdrop',
            error: 'error',
            'font-family': 'font-family',
            primary: 'primary',
            text: 'text',
            warning: 'warning',
          },
        },
        customer: { customer_id: 'customer_id', email: 'john.doe@example.com', phone_number: '+4799999999' },
        expires_at: '2019-12-27T18:11:19.117Z',
        metadata: '',
        profile_id: 'profile_id',
      },
      token_provider: { payment_product_type: 'payment_product_type' },
      include_session: true,
      'Dintero-System-Name': 'Dintero-System-Name',
      'Dintero-System-Plugin-Name': 'Dintero-System-Plugin-Name',
      'Dintero-System-Plugin-Version': 'Dintero-System-Plugin-Version',
      'Dintero-System-Version': 'Dintero-System-Version',
    });
  });
});
