// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import SpecPayments from 'spec-payments-stainless-demo';
import { Response } from 'node-fetch';

const client = new SpecPayments({
  accessToken: 'My Access Token',
  apiKey: 'My API Key',
  adminKey: 'My Admin Key',
  clientId: 'My Client ID',
  clientSecret: 'My Client Secret',
  baseURL: process.env['TEST_API_BASE_URL'] ?? 'http://127.0.0.1:4010',
});

describe('resource sessionsProfiles', () => {
  test('create: only required params', async () => {
    const responsePromise = client.sessionsProfiles.create({
      order: { merchant_reference: 'merchant_reference' },
      profile_id: 'profile_id',
      url: { return_url: 'https://example.com/accept' },
    });
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  test('create: required and optional params', async () => {
    const response = await client.sessionsProfiles.create({
      order: {
        merchant_reference: 'merchant_reference',
        amount: 72200,
        billing_address: {
          address_line: 'address_line',
          address_line_2: 'address_line_2',
          business_name: 'business_name',
          co_address: 'Land Lord',
          comment: 'comment',
          cost_center: 'cost_center',
          country: 'NO',
          customer_reference: 'customer_reference',
          email: 'email',
          first_name: 'John',
          last_name: 'Doe',
          latitude: 0,
          longitude: 0,
          organization_number: 'organization_number',
          organization_type: 'organization_type',
          phone_number: 'phone_number',
          postal_code: '0349',
          postal_place: 'Oslo',
        },
        currency: 'NOK',
        discount_codes: ['SUMMER20', 'SUMMER20', 'SUMMER20'],
        discount_lines: [
          {
            amount: 4400,
            description: 'description',
            discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
            discount_type: 'customer',
            line_id: 1,
            percentage: 44,
          },
          {
            amount: 4400,
            description: 'description',
            discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
            discount_type: 'customer',
            line_id: 1,
            percentage: 44,
          },
          {
            amount: 4400,
            description: 'description',
            discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
            discount_type: 'customer',
            line_id: 1,
            percentage: 44,
          },
        ],
        items: [
          {
            id: '10',
            amount: 2000,
            description: 'Forsvinnignspølse',
            discount_lines: [
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
            ],
            eligible_for_discount: true,
            emd: {
              event: [
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
              ],
              marketplace_order: {
                seller_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  product_category: 'Phones',
                  sub_merchant_id: 'Marketbrick Ltd.',
                  product_name: 'iPhone 14 Pro Max',
                  seller_rating: 5,
                  unique_account_identifier_seller: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
                winner_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  unique_account_identifier_winner: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
              },
              subscription: {
                customer_account_info: {
                  account_last_modified: 'account_last_modified',
                  account_registration_date: 'account_registration_date',
                  unique_account_identifier: 'Adam Adamsson',
                },
                subscription: {
                  auto_renewal_of_subscription: true,
                  end_time: '2019-12-27T18:11:19.117Z',
                  start_time: '2019-12-27T18:11:19.117Z',
                  subscription_name: 'Contact lenses',
                  affiliate_name: 'Klarna affiliate',
                },
              },
              travel: {
                air_reservation_details: {
                  itinerary: [
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                bus_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                car_rental_reservation_details: {
                  drivers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  itinerary: [
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  pnr: 'VH67899',
                },
                ferry_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                hotel_reservation_details: {
                  itinerary: [
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                train_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
              },
            },
            fee_split: { type: 'proportional', destinations: ['string'] },
            groups: [{ id: 'B234', name: 'Stol' }],
            is_changed: true,
            line_id: '1',
            quantity: 2,
            splits: [
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
            ],
            thumbnail_url: 'https://example.com',
            type: 'physical',
            unit_dimensional_weight: 0,
            unit_volume: 0,
            unit_weight: 0,
            vat: 20,
            vat_amount: 400,
          },
          {
            id: '6',
            amount: 6600,
            description: 'Vissvossafår på neppebrød',
            discount_lines: [
              {
                amount: 4400,
                description: 'Vossafestpris',
                discount_id: 'ed960ace-eb16-4e2e-ae52-b27647ccae8d',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
            ],
            eligible_for_discount: true,
            emd: {
              event: [
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
              ],
              marketplace_order: {
                seller_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  product_category: 'Phones',
                  sub_merchant_id: 'Marketbrick Ltd.',
                  product_name: 'iPhone 14 Pro Max',
                  seller_rating: 5,
                  unique_account_identifier_seller: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
                winner_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  unique_account_identifier_winner: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
              },
              subscription: {
                customer_account_info: {
                  account_last_modified: 'account_last_modified',
                  account_registration_date: 'account_registration_date',
                  unique_account_identifier: 'Adam Adamsson',
                },
                subscription: {
                  auto_renewal_of_subscription: true,
                  end_time: '2019-12-27T18:11:19.117Z',
                  start_time: '2019-12-27T18:11:19.117Z',
                  subscription_name: 'Contact lenses',
                  affiliate_name: 'Klarna affiliate',
                },
              },
              travel: {
                air_reservation_details: {
                  itinerary: [
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                bus_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                car_rental_reservation_details: {
                  drivers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  itinerary: [
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  pnr: 'VH67899',
                },
                ferry_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                hotel_reservation_details: {
                  itinerary: [
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                train_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
              },
            },
            fee_split: { type: 'proportional', destinations: ['string'] },
            groups: [{ id: 'B234', name: 'Stol' }],
            is_changed: true,
            line_id: '2',
            quantity: 2,
            splits: [
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
            ],
            thumbnail_url: 'https://example.com',
            type: 'physical',
            unit_dimensional_weight: 0,
            unit_volume: 0,
            unit_weight: 0,
            vat: 20,
            vat_amount: 400,
          },
          {
            id: '1',
            amount: 59700,
            description: 'Luftboller',
            discount_lines: [
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
              {
                amount: 4400,
                description: 'description',
                discount_id: '766da0ef-9283-42bd-b012-0582344ec53c',
                discount_type: 'customer',
                line_id: 1,
                percentage: 44,
              },
            ],
            eligible_for_discount: true,
            emd: {
              event: [
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
                {
                  end_time: '2019-12-27T18:11:19.117Z',
                  event_company: 'Diamond Events',
                  event_name: 'Michael Jackson',
                  genre_of_event: 'Pop',
                  start_time: '2019-12-27T18:11:19.117Z',
                  ticket_delivery_method: 'pick_up',
                  ticket_delivery_recipient: 'recipient@mail.com',
                  access_controlled_venue: true,
                  affiliate_name: 'Klarna affiliate',
                  arena_location: {
                    city: 'Oslo',
                    country: 'NO',
                    postal_code: '0185',
                    street_address: 'Sonja Henies plass 2',
                  },
                  arena_name: 'Oslo Spektrum',
                },
              ],
              marketplace_order: {
                seller_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  product_category: 'Phones',
                  sub_merchant_id: 'Marketbrick Ltd.',
                  product_name: 'iPhone 14 Pro Max',
                  seller_rating: 5,
                  unique_account_identifier_seller: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
                winner_info: {
                  account_last_modified: {
                    address: '2019-12-27T18:11:19.117Z',
                    email: '2019-12-27T18:11:19.117Z',
                    listing: '2019-12-27T18:11:19.117Z',
                    login: '2019-12-27T18:11:19.117Z',
                    password: '2019-12-27T18:11:19.117Z',
                  },
                  account_registration_date: '2019-12-27T18:11:19.117Z',
                  number_of_trades: 23,
                  unique_account_identifier_winner: {
                    email: 'email',
                    other: 'other',
                    phone_number: '97712123',
                  },
                  volume_of_trades: 230,
                },
              },
              subscription: {
                customer_account_info: {
                  account_last_modified: 'account_last_modified',
                  account_registration_date: 'account_registration_date',
                  unique_account_identifier: 'Adam Adamsson',
                },
                subscription: {
                  auto_renewal_of_subscription: true,
                  end_time: '2019-12-27T18:11:19.117Z',
                  start_time: '2019-12-27T18:11:19.117Z',
                  subscription_name: 'Contact lenses',
                  affiliate_name: 'Klarna affiliate',
                },
              },
              travel: {
                air_reservation_details: {
                  itinerary: [
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival: 'MUC',
                      carrier: 'LH',
                      departure: 'OSL',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      arrival_city: 'Munich',
                      class: 'First Class',
                      departure_city: 'Oslo',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                bus_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Bus Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                car_rental_reservation_details: {
                  drivers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  itinerary: [
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                    {
                      end_time: 'end_time',
                      rental_company: 'Premium Cars',
                      start_time: 'start_time',
                      car_price: 500000,
                      class: 'Premium Cars Premium Class',
                      drivers_id: [1],
                      drop_off_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      pick_up_location: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  pnr: 'VH67899',
                },
                ferry_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Ferry Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      passenger_id: [1],
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                hotel_reservation_details: {
                  itinerary: [
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                    {
                      end_time: 'end_time',
                      hotel_price: 200000,
                      number_of_rooms: 2,
                      passenger_id: [1],
                      start_time: 'start_time',
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      address: {
                        city: 'Oslo',
                        country: 'NO',
                        postal_code: '0159',
                        street_address: 'Karl Johans gt. 31',
                      },
                      class: 'First Class',
                      hotel_name: 'Premium Hotel',
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
                train_reservation_details: {
                  itinerary: [
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                    {
                      arrival_city: 'Munich',
                      carrier: 'Big Train Travels Ltd.',
                      departure_city: 'Oslo',
                      departure_date: 'departure_date',
                      passenger_id: [1],
                      ticket_delivery_method: 'pick_up',
                      ticket_delivery_recipient: '97712123',
                      class: 'First Class',
                      segment_price: 200000,
                    },
                  ],
                  affiliate_name: 'Klarna affiliate',
                  insurance: [
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                    {
                      insurance_company: 'Oopsie Insurance Ltd.',
                      insurance_price: 50000,
                      insurance_type: 'cancellation',
                    },
                  ],
                  passengers: [
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                    { first_name: 'Paul', last_name: 'Lamb', id: 1, title: 'mr' },
                  ],
                  pnr: 'VH67899',
                },
              },
            },
            fee_split: { type: 'proportional', destinations: ['string'] },
            groups: [{ id: 'B234', name: 'Stol' }],
            is_changed: true,
            line_id: '3',
            quantity: 3,
            splits: [
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
              { amount: 29700, payout_destination_id: 'P000000001' },
            ],
            thumbnail_url: 'https://example.com',
            type: 'physical',
            unit_dimensional_weight: 0,
            unit_volume: 0,
            unit_weight: 0,
            vat: 20,
            vat_amount: 400,
          },
        ],
        merchant_reference_2: 'merchant_reference_2',
        partial_payment: true,
        payout_destination_id: 'payout_destination_id',
        shipping_address: {
          address_line: 'address_line',
          address_line_2: 'address_line_2',
          business_name: 'business_name',
          co_address: 'Land Lord',
          comment: 'comment',
          cost_center: 'cost_center',
          country: 'NO',
          customer_reference: 'customer_reference',
          email: 'email',
          first_name: 'John',
          last_name: 'Doe',
          latitude: 0,
          longitude: 0,
          organization_number: 'organization_number',
          organization_type: 'organization_type',
          phone_number: 'phone_number',
          postal_code: '0349',
          postal_place: 'Oslo',
        },
        shipping_option: {
          id: 'bring-pick-up-00001',
          amount: 3900,
          line_id: 'bring-pick-up-00001-location-0a1f6b',
          operator: 'Bring',
          title: 'Standard',
          countries: ['NO', 'NO', 'NO'],
          delivery_method: 'delivery',
          description: 'Pick up at your nearest postal office',
          environmental_data: {
            description: 'Fossil free',
            details: [
              { label: 'Carbon offset', value: '1KG CO2' },
              { label: 'Carbon offset', value: '1KG CO2' },
              { label: 'Carbon offset', value: '1KG CO2' },
            ],
          },
          eta: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
          fee_split: { type: 'proportional', destinations: ['string'] },
          metadata: '',
          operator_product_id: 'pick-up-00001-location-0a1f6b',
          pick_up_address: {
            address_line: 'address_line',
            address_line_2: 'address_line_2',
            business_name: 'business_name',
            co_address: 'Land Lord',
            comment: 'comment',
            cost_center: 'cost_center',
            country: 'NO',
            customer_reference: 'customer_reference',
            distance: 0,
            email: 'email',
            first_name: 'John',
            last_name: 'Doe',
            latitude: 0,
            longitude: 0,
            organization_number: 'organization_number',
            organization_type: 'organization_type',
            phone_number: 'phone_number',
            postal_code: '0349',
            postal_place: 'Oslo',
          },
          splits: [
            { amount: 29700, payout_destination_id: 'P000000001' },
            { amount: 29700, payout_destination_id: 'P000000001' },
            { amount: 29700, payout_destination_id: 'P000000001' },
          ],
          thumbnail_url: 'https://example.com',
          time_slot: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
          vat: 25,
          vat_amount: 975,
        },
        store: {
          id: 'sc029',
          address: {
            address_line: 'Sommerkroveien 34',
            country: 'NO',
            postal_place: 'Oslo',
            address_line_2: 'PB 123',
            postal_code: '0349',
          },
          bax: '102603',
          business_name: 'SC Oslo AS',
          chain: 'SuperChain',
          email: 'contact@superchain.com',
          gln: '5790001398644',
          mcc: '5814',
          name: 'SC Oslo',
          organization_number: '123456789MVA',
          phone_number: '+4738260107',
          terminal_id: 'T0292',
        },
        vat_amount: 13660,
      },
      profile_id: 'profile_id',
      url: {
        return_url: 'https://example.com/accept',
        callback_url: 'https://example.com/callback?method=GET',
        merchant_terms_url: 'https://example.com/terms.html',
      },
      include_session: true,
      checkboxes: [
        {
          id: 'id',
          label: 'xx',
          checked: true,
          link: { text: 'Terms for checkbox action', url: 'url' },
          required: true,
        },
        {
          id: 'id',
          label: 'xx',
          checked: true,
          link: { text: 'Terms for checkbox action', url: 'url' },
          required: true,
        },
      ],
      configuration: {
        active_payment_types: { enabled: true },
        allow_different_billing_shipping_address: ['b2c', 'b2b'],
        auto_capture: true,
        bambora: {
          creditcard: {
            enabled: true,
            generate_payment_token: true,
            generate_recurrence_token: true,
            payability: 'payable',
            type: 'payment_product_type',
          },
          mobilepay: { enabled: true, payability: 'payable', type: 'payment_product_type' },
          type: 'payment_type',
          vipps: { enabled: true, payability: 'payable', type: 'payment_product_type' },
        },
        channel: 'in_app',
        collector: {
          dynamic_descriptor: 'dynamic_descriptor',
          finance: {
            enabled: true,
            countries: ['string', 'string', 'string'],
            payability: 'payable',
            type: 'payment_product_type',
          },
          installment: {
            enabled: true,
            countries: ['string', 'string', 'string'],
            options: { enable_on_hold: true },
            payability: 'payable',
            type: 'payment_product_type',
          },
          invoice: {
            enabled: true,
            countries: ['string', 'string', 'string'],
            options: { enable_on_hold: true },
            payability: 'payable',
            type: 'payment_product_type',
          },
          invoice_b2b: {
            enabled: true,
            countries: ['string', 'string', 'string'],
            options: { disable_collector_b2b_address_enforcement: true, enable_on_hold: true },
            payability: 'payable',
            type: 'payment_product_type',
          },
          invoice_b2b_preapproved: {
            enabled: true,
            accounts: [
              {
                billing_address: {
                  address_line: 'address_line',
                  business_name: 'business_name',
                  country: 'NO',
                  email: 'email',
                  organization_number: 'xxxxxxxxx',
                  phone_number: 'phone_number',
                  postal_code: '0349',
                  postal_place: 'Oslo',
                  address_id: 'address_1',
                  address_line_2: 'address_line_2',
                  co_address: 'co_address',
                  cost_center: 'cost_center',
                  customer_reference: 'customer_reference',
                  first_name: 'John',
                  last_name: 'Doe',
                },
                company_id: 'company_id',
              },
              {
                billing_address: {
                  address_line: 'address_line',
                  business_name: 'business_name',
                  country: 'NO',
                  email: 'email',
                  organization_number: 'xxxxxxxxx',
                  phone_number: 'phone_number',
                  postal_code: '0349',
                  postal_place: 'Oslo',
                  address_id: 'address_1',
                  address_line_2: 'address_line_2',
                  co_address: 'co_address',
                  cost_center: 'cost_center',
                  customer_reference: 'customer_reference',
                  first_name: 'John',
                  last_name: 'Doe',
                },
                company_id: 'company_id',
              },
              {
                billing_address: {
                  address_line: 'address_line',
                  business_name: 'business_name',
                  country: 'NO',
                  email: 'email',
                  organization_number: 'xxxxxxxxx',
                  phone_number: 'phone_number',
                  postal_code: '0349',
                  postal_place: 'Oslo',
                  address_id: 'address_1',
                  address_line_2: 'address_line_2',
                  co_address: 'co_address',
                  cost_center: 'cost_center',
                  customer_reference: 'customer_reference',
                  first_name: 'John',
                  last_name: 'Doe',
                },
                company_id: 'company_id',
              },
            ],
            countries: ['string', 'string', 'string'],
            payability: 'payable',
            type: 'payment_product_type',
          },
          type: 'payment_type',
        },
        countries: {
          allow_countries: ['string', 'string', 'string'],
          deny_countries: ['string', 'string', 'string'],
          preferred_country: 'preferred_country',
        },
        default_customer_type: 'b2c',
        default_payment_type: 'bambora.creditcard',
        dintero: {
          type: 'payment_type',
          wallets: { enabled: true, payability: 'payable', type: 'payment_product_type' },
          zero: { enabled: true, payability: 'payable', type: 'payment_product_type' },
        },
        dintero_psp: {
          creditcard: { enabled: true, payability: 'payable', type: 'payment_product_type' },
          type: 'payment_type',
        },
        discounts: {
          express_discount_codes: { enabled: true, payability: 'payable' },
          order: { enabled: true },
        },
        instabank: {
          finance: {
            enabled: true,
            payability: 'payable',
            product: {
              loan_example: { amount: 2500000, cost: 272300, total_amount: 2772300, years: 1 },
              minimum_monthly_balance_rate: '1.67',
              notification_fee: 3900,
              origination_fee: 9500,
              product_code: '630',
              annual_interest_rate: '0.0',
              branding_image_url: 'branding_image_url',
              minimum_amount: 20000,
            },
          },
          installment: { enabled: true, payability: 'payable', type: 'payment_product_type' },
          invoice: {
            enabled: true,
            payability: 'payable',
            product: {
              due_in_days: 10,
              invoice_fee: 9500,
              product_code: '632',
              require_applicant_amount: 7500000,
              branding_image_url: 'branding_image_url',
              minimum_amount: 20000,
            },
            require_applicant: true,
          },
          postponement: { enabled: true, payability: 'payable', type: 'payment_product_type' },
        },
        klarna: {
          billie: { enabled: true, payability: 'payable', type: 'payment_product_type' },
          klarna: { enabled: true, payability: 'payable', type: 'payment_product_type' },
          type: 'payment_type',
        },
        netaxept: {
          creditcard: {
            enabled: true,
            payability: 'payable',
            terminal: {
              terminal: '/Terminal/default.aspx',
              terminal_single_page: true,
              terminal_design: 'terminal_design',
              terminal_layout: 'terminal_layout',
            },
            type: 'payment_product_type',
          },
          type: 'payment_type',
        },
        payex: {
          applepay: { enabled: true, payability: 'payable', type: 'payment_product_type' },
          clicktopay: { enabled: true, payability: 'payable', type: 'payment_product_type' },
          creditcard: {
            enabled: true,
            generate_payment_token: true,
            generate_recurrence_token: true,
            no_cvc: true,
            payability: 'payable',
          },
          dynamic_descriptor: 'dynamic_descriptor',
          googlepay: { enabled: true, payability: 'payable', type: 'payment_product_type' },
          mobilepay: { enabled: true, payability: 'payable' },
          swish: { enabled: true, payability: 'payable' },
          vipps: { enabled: true, payability: 'payable' },
        },
        payout: {
          dynamic_payout_destination_ids: [
            { order_payout_destination_id: 'PD_123', order_store_id: 'STORE_123', type: 'order_store_id' },
          ],
        },
        publish: [
          { channel: 'sms', type: 'checkout-link' },
          { channel: 'sms', type: 'checkout-link' },
          { channel: 'sms', type: 'checkout-link' },
        ],
        santander: {
          debit_account: {
            enabled: true,
            accounts: [
              {
                account_number_token: 'account_number_token',
                masked_account_number: 'masked_account_number',
              },
              {
                account_number_token: 'account_number_token',
                masked_account_number: 'masked_account_number',
              },
              {
                account_number_token: 'account_number_token',
                masked_account_number: 'masked_account_number',
              },
            ],
            branding_name: 'branding_name',
            payability: 'payable',
            type: {},
          },
          type: 'payment_type',
        },
        swish: {
          swish: { enabled: true, payability: 'payable', type: 'payment_product_type' },
          type: 'payment_type',
        },
        theme: {
          backdrop: 'backdrop',
          error: 'error',
          'font-family': 'font-family',
          primary: 'primary',
          text: 'text',
          warning: 'warning',
        },
        vipps: { enabled: true, dynamic_descriptor: 'dynamic_descriptor', payability: 'payable' },
      },
      customer: {
        customer_id: 'customer_id',
        email: 'john.doe@example.com',
        gift_cards: { 'dintero.wallets': [{ card_id: 'card_id' }] },
        phone_number: '+4799999999',
        tokens: {
          'bambora.creditcard': { payment_token: 'payment_token', recurrence_token: 'recurrence_token' },
          'payex.creditcard': { payment_token: 'payment_token', recurrence_token: 'recurrence_token' },
        },
      },
      expires_at: '2019-12-27T18:11:19.117Z',
      express: {
        shipping_options: [
          {
            id: 'bring-pick-up-00001',
            amount: 3900,
            line_id: 'bring-pick-up-00001-location-0a1f6b',
            operator: 'Bring',
            title: 'Standard',
            countries: ['NO', 'NO', 'NO'],
            delivery_method: 'delivery',
            description: 'Pick up at your nearest postal office',
            environmental_data: {
              description: 'Fossil free',
              details: [
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
              ],
            },
            eta: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            metadata: '',
            operator_product_id: 'pick-up-00001-location-0a1f6b',
            pick_up_address: {
              address_line: 'address_line',
              address_line_2: 'address_line_2',
              business_name: 'business_name',
              co_address: 'Land Lord',
              comment: 'comment',
              cost_center: 'cost_center',
              country: 'NO',
              customer_reference: 'customer_reference',
              distance: 0,
              email: 'email',
              first_name: 'John',
              last_name: 'Doe',
              latitude: 0,
              longitude: 0,
              organization_number: 'organization_number',
              organization_type: 'organization_type',
              phone_number: 'phone_number',
              postal_code: '0349',
              postal_place: 'Oslo',
            },
            thumbnail_url: 'https://example.com',
            time_slot: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            vat: 25,
            vat_amount: 975,
          },
          {
            id: 'bring-pick-up-00001',
            amount: 3900,
            line_id: 'bring-pick-up-00001-location-0a1f6b',
            operator: 'Bring',
            title: 'Standard',
            countries: ['NO', 'NO', 'NO'],
            delivery_method: 'delivery',
            description: 'Pick up at your nearest postal office',
            environmental_data: {
              description: 'Fossil free',
              details: [
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
              ],
            },
            eta: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            metadata: '',
            operator_product_id: 'pick-up-00001-location-0a1f6b',
            pick_up_address: {
              address_line: 'address_line',
              address_line_2: 'address_line_2',
              business_name: 'business_name',
              co_address: 'Land Lord',
              comment: 'comment',
              cost_center: 'cost_center',
              country: 'NO',
              customer_reference: 'customer_reference',
              distance: 0,
              email: 'email',
              first_name: 'John',
              last_name: 'Doe',
              latitude: 0,
              longitude: 0,
              organization_number: 'organization_number',
              organization_type: 'organization_type',
              phone_number: 'phone_number',
              postal_code: '0349',
              postal_place: 'Oslo',
            },
            thumbnail_url: 'https://example.com',
            time_slot: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            vat: 25,
            vat_amount: 975,
          },
          {
            id: 'bring-pick-up-00001',
            amount: 3900,
            line_id: 'bring-pick-up-00001-location-0a1f6b',
            operator: 'Bring',
            title: 'Standard',
            countries: ['NO', 'NO', 'NO'],
            delivery_method: 'delivery',
            description: 'Pick up at your nearest postal office',
            environmental_data: {
              description: 'Fossil free',
              details: [
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
                { label: 'Carbon offset', value: '1KG CO2' },
              ],
            },
            eta: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            metadata: '',
            operator_product_id: 'pick-up-00001-location-0a1f6b',
            pick_up_address: {
              address_line: 'address_line',
              address_line_2: 'address_line_2',
              business_name: 'business_name',
              co_address: 'Land Lord',
              comment: 'comment',
              cost_center: 'cost_center',
              country: 'NO',
              customer_reference: 'customer_reference',
              distance: 0,
              email: 'email',
              first_name: 'John',
              last_name: 'Doe',
              latitude: 0,
              longitude: 0,
              organization_number: 'organization_number',
              organization_type: 'organization_type',
              phone_number: 'phone_number',
              postal_code: '0349',
              postal_place: 'Oslo',
            },
            thumbnail_url: 'https://example.com',
            time_slot: { ends_at: '2019-12-27T18:11:19.117Z', starts_at: '2019-12-27T18:11:19.117Z' },
            vat: 25,
            vat_amount: 975,
          },
        ],
        customer_types: ['b2c', 'b2b'],
        discount_codes: {
          callback_url: 'https://example.com/order/00128110/discount_codes_updated',
          max_count: 0,
        },
        shipping_address_callback_url: 'https://example.com/order/00128110/address_updated',
        shipping_mode: 'shipping_required',
      },
      merchant: {
        logo_url: 'https://example.com',
        name: 'name',
        address_line: 'address_line',
        address_line_2: 'address_line_2',
        country: 'country',
        email: 'email',
        merchant_category_code: 'merchant_category_code',
        phone_number: 'phone_number',
        postal_code: 'postal_code',
        postal_place: 'postal_place',
        website: 'website',
      },
      metadata: '',
      'Dintero-Feature-Toggles': ['strict-session-amounts'],
      'Dintero-System-Name': 'Dintero-System-Name',
      'Dintero-System-Plugin-Name': 'Dintero-System-Plugin-Name',
      'Dintero-System-Plugin-Version': 'Dintero-System-Plugin-Version',
      'Dintero-System-Version': 'Dintero-System-Version',
    });
  });
});
